name: deploy to s3
on:
  push:
    branches:
      - main
jobs:
  pipeline:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 8
    permissions:
      id-token: write
      contents: read
    env:
      CF_DIST_ID: E2IM9KF6CQIU9O
      ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/CICDS3Portfolio
      BUCKET: locky.ar
      BUILD_FOLDER: ./dist/locky/browser
    steps:
      - uses: actions/checkout@v4

      - name: set up aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: us-east-1

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: get dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: go to build folder
        run: cd ${{ env.BUILD_FOLDER }}

      - name: Deploy to AWS S3
        run: aws s3 sync . s3://${{ env.BUCKET }} --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CF_DIST_ID }} --paths /index.html
